raptor/config/routes.rb
Raptor::Application.routes.draw do
  resources :tweets

  resources :matchups

  resources :players

  resources :teams

  root 'teams#index'

  

end

raptor/app/models/helpers/matchups_helper.rb
module MatchupsHelper
end

raptor/app/models/matchup.rb
class Matchup < ActiveRecord::Base
  require 'net/http'
  require 'rexml/document'
  
	def self.get_weekly_schedule(week)
  		week = week.to_s
        	uri = URI.parse("http://api.sportsdatallc.org/nfl-t1/2013/REG/3/schedule.xml?api_key=dxd35qzuacv8g262jh4uhq6t")
        	http = Net::HTTP.new(uri.host, uri.port)
       	        request = Net::HTTP::Get.new(uri.request_uri)

        	response = http.request(request)

       	 	xml = response.body
	
		doc = REXML::Document.new xml
        	games = doc.get_elements('//game')

        	games.each do |game|
          	 time = game.attributes["scheduled"]
          	 home_symbol = game.attributes["home"]
          	 away_symbol = game.attributes["away"]
          
         	 m = Matchup.create( :week => week, :home_symbol => home_symbol, :away_symbol => away_symbol, :time => time)
       		 end
  	 end 
	
	def parse_time(datetime)
		datetime.strftime("%A  %I:%M %p %Z")
		
	end 
end

raptor/app/controllers/matchups_controller.rb
class MatchupsController < ApplicationController
  before_action :set_matchup, only: [:show, :edit, :update, :destroy]

  # GET /matchups
  # GET /matchups.json
  def index
    @matchups = Matchup.all
  end

  # GET /matchups/1
  # GET /matchups/1.json
  def show
    @home = Team.find(1)
    @away = Team.find(12)
  end

  # GET /matchups/new
  def new
    @matchup = Matchup.new
  end

  # GET /matchups/1/edit
  def edit
  end

  # POST /matchups
  # POST /matchups.json
  def create
    @matchup = Matchup.new(matchup_params)

    respond_to do |format|
      if @matchup.save
        format.html { redirect_to @matchup, notice: 'Matchup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @matchup }
      else
        format.html { render action: 'new' }
        format.json { render json: @matchup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matchups/1
  # PATCH/PUT /matchups/1.json
  def update
    respond_to do |format|
      if @matchup.update(matchup_params)
        format.html { redirect_to @matchup, notice: 'Matchup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @matchup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matchups/1
  # DELETE /matchups/1.json
  def destroy
    @matchup.destroy
    respond_to do |format|
      format.html { redirect_to matchups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matchup
      @matchup = Matchup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matchup_params
      params.require(:matchup).permit(:time, :home_id, :away_id, :home_symbol, :home_symbol, :away_symbol)
    end
end

raptor/app/views/matchups/_form.html.erb
<%= form_for(@matchup) do |f| %>
  <% if @matchup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@matchup.errors.count, "error") %> prohibited this matchup from being saved:</h2>

      <ul>
      <% @matchup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :home_id %><br>
    <%= f.number_field :home_id %>
  </div>
  <div class="field">
    <%= f.label :away_id %><br>
    <%= f.number_field :away_id %>
  </div>
  <div class="field">
    <%= f.label :home_symbol %><br>
    <%= f.text_field :home_symbol %>
  </div>
  <div class="field">
    <%= f.label :home_symbol %><br>
    <%= f.text_field :home_symbol %>
  </div>
  <div class="field">
    <%= f.label :away_symbol %><br>
    <%= f.text_field :away_symbol %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

raptor/app/views/matchups/edit.html.erb
<h1>Editing matchup</h1>

<%= render 'form' %>

<%= link_to 'Show', @matchup %> |
<%= link_to 'Back', matchups_path %>

raptor/app/views/matchups/index.html.erb
<h1>NFL Week <% unless @matchups.empty? %>
  <%= @matchups.first.week %>
  <% end %>
</h1>

<table class="table" >
  <thead>
    <tr>
      <th>Time</th>
      <th></th>
      <th></th>  
      <th>Matchup</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matchups.each do |matchup| %>
       <tr> 
	<td><%= matchup.parse_time(matchup.time) %></td>
        <td><%= matchup.home_id %></td>
        <td><%= matchup.away_id %></td>
        <td><%= matchup.home_symbol %> vs. <%= matchup.away_symbol %></td>
        <td>
          <% if(matchup.id==27) %>
            <%=link_to 'Show', matchup %>
    <% end%>
          </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

raptor/app/views/matchups/new.html.erb
<h1>New matchup</h1>

<%= render 'form' %>

<%= link_to 'Back', matchups_path %>

raptor/app/views/matchups/show.html.erb
<p id="notice"><%= notice %></p>

<p class="symbol">
  <%= @matchup.home_symbol %>
      vs.
  <%= @matchup.away_symbol %>
</p>
<p>                                                                                                                                                            
  <strong>Time:</strong>                                                                                                                                       
  <%= @matchup.time %>                                                                                                                                         
</p>     
  
<table id="players-faces-left" class="table table-striped">
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><h3><%= @home.week_sentiment %></h3></td>
    </tr>
  <% @home.player_sentiments.each do |player, sentiment| %>
    <tr>
      <td>
      <%= link_to player.name, player %></br>
      <% if sentiment > 0.25 %>
        <div class='smiley-green'>
      <% elsif sentiment < -0.25 %>
        <div class='smiley-red'>
      <% else %>
        <div class='smiley-yellow'>
      <% end %>
        <div class="left-eye"></div>
        <div class="right-eye"></div>
        <div class="smile"></div>
      </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>


<table id="players-faces-right" class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <td><h3><%= @away.week_sentiment %></h3></td>
  <% @away.player_sentiments.each do |player, sentiment| %>
    <tr>
      <td>
      <%= link_to player.name, player %></br>
      <% if sentiment > 0.25 %>
        <div class='smiley-green'>
      <% elsif sentiment < -0.25 %>
        <div class='smiley-red'>
      <% else %>
        <div class='smiley-yellow'>
      <% end %>
        <div class="left-eye"></div>
        <div class="right-eye"></div>
        <div class="smile"></div>
      </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>